config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'books#index'
end

#
# Rails.application.routes.draw do
#   resources :books do
#     collection do
#       get "genres/:genre", action: :genre, as: :genre
#     end
#   end
# end
#
# get "/books/genres/:genre", controller: :books, action: :genre, as: :genre

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  # has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_login, only: [:show, :edit, :update, :new, :destroy]
  before_action :book_owner, only: [:edit, :update, :destroy]


  def index
    @books = Book.all
  end

  def show
    set_book
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @user = User.find_by(id: session[:user_id])
    @book = @user.books.new(book_params)
    # redirect_to books_path(@book)
    # @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @book = Book.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_book
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def genre
  #   @books = Book.where(genre: params[:genres])
  # end

  private
    def require_login
      redirect_to login_path unless logged_in?
    end

    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:id, :title, :author, :description, :URL)
    end

    def book_owner
      set_book
      redirect_to books_path unless @book.user_id == current_user.id
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      render 'new'
    end
  end
  # def sign_out
  #   reset_session
  #   redirect_to root_url
  # end
  #
  def destroy
    reset_session
    render 'log_out'
  end
end


# # Taken from console after submitting a username and password that was stored in the User db
  # Parameters: {
  #   "utf8"=>"✓", "authenticity_token"=>"bvDny5fV/L9TJcTyb8ptPpW7jINXHNfoYCwhAMaS5e3XMffy4z0YFpxsqtBTxq8ghH9zoE6u3uU3y4bilEuzMg==",
  #   "session"=>{
  #      "email"=>"ginnie@yahoo.com",
  #       "password"=>"[FILTERED]"
  #     },
  #   "commit"=>"Log in"
  # }

# Create method example from newline
  # def create
  #   user = User.find_by(name: params[:name])
  #   if user.authenticate(params[:password])
  #     session[:user_id] = user.id
  #     redirect_to user
  #   else
  #     render 'new'
  #   end
  # end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_login, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def is_user?

      redirect_to books_path unless @user.id == current_user.id
    end
end


# See Listing 7.28

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :url %><br>
    <%= form.text_field :url %>
  </p>

  <p>
    <%= form.label :user_id %><br>
    <%= form.text_field :user_id %>
  </p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%=book.title        %></td>
        <td><%=book.author        %></td>
        <td><%=book.description        %></td>
        <td><%=book.URL        %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>
<br />
<% if logged_in? %>
     <span><%= link_to "Users", '#' %></span>   <span><%= link_to "Log out", logout_path, method: :delete %></span>
<% else %>
  <p><%= link_to "Log in", login_path %></p>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%=@book.title %>
  <br>
  <%=@book.author %>
  <br>
  <%=@book.description %>
  <br>
  <%=@book.URL %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %>
<br>
<%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' } %>
<br>
<%= link_to 'New Book', new_book_path %>
<br>
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freeshelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<p>Already registered? <%= link_to "Login", login_path %></p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

<p><%= link_to "Book index", books_path %></p>